Update BSP submodule: Remove PCF2131 patch reference
Fixed kernel build failure caused by referencing deleted PCF2131 patch.
LmP v95.2 with kernel 6.6+ has native PCF2131 support, so the custom
patch is no longer needed.

This should resolve build 2169 failure:
ERROR: Unable to get checksum for linux-lmp-fslc-imx SRC_URI entry
0007-rtc-pcf2127-add-support-for-PCF2131-RTC.patch: file could not be found